First commit for #8
astrutz/eloglicko pull request #9
Opened 2021-11-06 11:59 UTC by Snapstromegon

Adds impls. for Player, PlayerRating and Ranking

2021-11-07 10:21 UTC, astrutz commented on src/class/Ranking.js
> +  getRandomOpponentMatches() {
Wäre Match-Erzeugung nicht besser in einem eigenen Modul ausgelagert?

2021-11-08 14:52 UTC, astrutz requested changes

2021-11-08 14:52 UTC, astrutz commented on src/class/MatchMaker.js
> +export default class MatchMaker {
Naming ist ausbaufähig. Tournament oder TournamentRound oder MatchRound fände ich hier besser. Vorallem weil Klassen eigentlich nach Nomen benannt sein sollten (nach BC-Standards)

2021-11-08 15:10 UTC, Snapstromegon commented on src/class/MatchMaker.js
> +export default class MatchMaker {
Ich möchte es explizit nicht mit Tournament nennen, da unsere zwei hauptsächlich betrachteten Systeme eben nicht das Konzept von Tournaments oder gar runden kennen.

Des weiteren ist MatchMaker für mich ein Nomen ^^.
Eventuell MatchManager als Alternative.

2021-11-09 07:19 UTC, merged